using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.DotnetRuntime.Extensions;

namespace VitalRouter.SourceGenerator;

[Generator]
public class VitalRouterIncrementalSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The transform reduces each [Routes] type to a fully value-equatable TypeModel.
        // Crucially we do NOT .Combine(CompilationProvider) and do NOT .Collect():
        // - Combining with the compilation would invalidate every keystroke anywhere.
        // - Collect would re-run all types whenever any one of them changes.
        // ReferenceSymbols is resolved here, from the per-node semantic model, so the
        // compilation dependency stays inside the transform and never reaches the output.
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                context,
                "VitalRouter.RoutesAttribute",
                static (node, _) => node is ClassDeclarationSyntax,
                static (context, _) =>
                {
                    var references = ReferenceSymbols.Create(context.SemanticModel.Compilation);
                    return references is null ? null : Parser.Parse(context, references);
                })
            .Where(static model => model is not null)
            .WithTrackingName("VitalRouter.RoutesProvider");

        // Per-type source output. Re-runs only when that type's TypeModel changes
        // by value, i.e. when a [Route] signature (name, command type, async-ness,
        // parameters, interceptors) changes — not when a method body is edited.
        context.RegisterSourceOutput(provider, static (sourceProductionContext, model) =>
        {
            Emit(model!, sourceProductionContext);
        });
    }

    static void Emit(TypeModel model, in SourceProductionContext context)
    {
        foreach (var diagnostic in model.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (model.HasError)
        {
            return;
        }

        if (model.Routes.Count <= 0)
        {
            return;
        }

        try
        {
            var builder = new StringBuilder();

            builder.AppendLine("""
// <auto-generated />
#nullable enable
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602 // Possible null return
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using VitalRouter;
using VitalRouter.Internal;

""");

            if (model.Namespace is not null)
            {
                builder.AppendLine($$"""
namespace {{model.Namespace}}
{
""");
            }

            builder.AppendLine($$"""
partial class {{model.TypeName}}
{
""");
            TryEmitMappingMethod(model, builder);
            TryEmitSubscriber(model, builder);
            TryEmitAsyncSubscriber(model, builder);
            TryEmitAsyncSubscriberCore(model, builder);

            builder.AppendLine("""
}
""");
            if (model.Namespace is not null)
            {
                builder.AppendLine("}");
            }

            builder.AppendLine($$"""
#pragma warning restore CS0162 // Unreachable code
#pragma warning restore CS0219 // Variable assigned but never used
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning restore CS8601 // Possible null reference assignment
#pragma warning restore CS8602 // Possible null return
#pragma warning restore CS8604 // Possible null reference argument for parameter
#pragma warning restore CS8631 // The type cannot be used as type parameter in the generic type or method
""");

            context.AddSource($"{model.HintName}.g.cs", builder.ToString());
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.UnexpectedErrorDescriptor,
                Location.None,
                ex.ToString()));
        }
    }

    static void TryEmitMappingMethod(TypeModel model, StringBuilder builder)
    {
        var parameters = new[] { "ICommandSubscribable subscribable" }
            .Concat(model.AllInterceptors.Select(x => $"{x.FullTypeName} {x.VariableName}"))
            .Distinct();

        builder.AppendLine($$"""
    readonly List<Subscription> vitalRouterGeneratedSubscriptions = new List<Subscription>();

    [global::VitalRouter.Preserve]
    public Subscription MapTo({{string.Join(", ", parameters)}})
    {
        UnmapRoutes();

""");
        var hasSubscriber = model.DefaultInterceptors.Count <= 0 &&
                            model.Routes.Any(x => !x.IsAsync && x.Interceptors.Count <= 0);
        var hasAsyncSubscriber = model.DefaultInterceptors.Count > 0 ||
                                 model.Routes.Any(x => x.IsAsync || x.Interceptors.Count > 0);
        if (hasSubscriber)
        {
            builder.AppendLine($$"""
        var subscriber = new VitalRouterGeneratedSubscriber(this);
        subscribable.Subscribe(subscriber);
""");
        }
        if (hasAsyncSubscriber)
        {
            var asyncSubscriberArgs = new[] { "this" }
                .Concat(model.AllInterceptors.Select(x => $"{x.VariableName}"))
                .Distinct();

            builder.AppendLine($$"""
        var asyncSubscriber  = new VitalRouterGeneratedAsyncSubscriber({{string.Join(", ", asyncSubscriberArgs)}});
        subscribable.Subscribe(asyncSubscriber);
""");
        }

        var subscriptionArgs = (hasSubscriber, hasAsyncSubscriber) switch
        {
            (true, true) => "subscriber, asyncSubscriber",
            (true, false) => "subscriber",
            (false, true) => "asyncSubscriber",
            _ => throw new InvalidOperationException()
        };

        builder.AppendLine($$"""
        var subscription = new Subscription(subscribable, {{subscriptionArgs}});
""");

        if (model.InheritsMonoBehaviour)
        {
            builder.AppendLine($$"""

        if (!gameObject.TryGetComponent(typeof(VitalRouter.Unity.SubscriptionHandle), out var handle))
        {
            handle = gameObject.AddComponent<VitalRouter.Unity.SubscriptionHandle>();
        }
        ((VitalRouter.Unity.SubscriptionHandle)handle).Subscriptions.Add(subscription);
""");
        }
        builder.AppendLine($$"""
        lock (vitalRouterGeneratedSubscriptions)
        {
            vitalRouterGeneratedSubscriptions.Add(subscription);
        }
        return subscription;
    }

    [global::VitalRouter.Preserve]
    public void UnmapRoutes()
    {
        lock (vitalRouterGeneratedSubscriptions)
        {
            foreach (var subscription in vitalRouterGeneratedSubscriptions)
            {
                subscription.Dispose();
            }
            vitalRouterGeneratedSubscriptions.Clear();
        }
    }

""");
    }

    static void TryEmitSubscriber(TypeModel model, StringBuilder builder)
    {
        if (model.DefaultInterceptors.Count > 0)
        {
            return;
        }

        var methods = model.Routes
            .Where(x => x is { IsAsync: false } && x.Interceptors.Count <= 0)
            .ToArray();

        if (!methods.Any())
        {
            return;
        }

        builder.AppendLine($$"""
    class VitalRouterGeneratedSubscriber : ICommandSubscriber
    {
        static class MethodTable<T> where T : ICommand
        {
            public static Action<{{model.TypeName}}, T, PublishContext>? Value;
        }

        static VitalRouterGeneratedSubscriber()
        {
""");
        foreach (var method in methods)
        {
            if (method.TakePublishContext)
            {
                builder.AppendLine($$"""
            MethodTable<{{method.CommandFullTypeName}}>.Value = static (source, command, ctx) => source.{{method.MethodName}}(command, ctx);
""");
            }
            else if (method.TakeCancellationToken)
            {
                builder.AppendLine($$"""
            MethodTable<{{method.CommandFullTypeName}}>.Value = static (source, command, ctx) => source.{{method.MethodName}}(command, ctx.CancellationToken);
""");
            }
            else
            {
                builder.AppendLine($$"""
            MethodTable<{{method.CommandFullTypeName}}>.Value = static (source, command, ctx) => source.{{method.MethodName}}(command);
""");
            }
        }

        builder.AppendLine($$"""
        }

        readonly {{model.TypeName}} source;

        public VitalRouterGeneratedSubscriber({{model.TypeName}} source)
        {
            this.source = source;
        }

        public void Receive<T>(T command, PublishContext context) where T : ICommand
        {
            MethodTable<T>.Value?.Invoke(source, command, context);
        }
    }

""");
    }

    static void TryEmitAsyncSubscriber(TypeModel model, StringBuilder builder)
    {
        var methods = model.DefaultInterceptors.Count > 0
            ? model.Routes.ToArray()
            : model.Routes.Where(x => x.Interceptors.Count > 0 || x.IsAsync).ToArray();

        if (!methods.Any())
        {
            return;
        }

        var interceptorParams = model.AllInterceptors.Select(x => $"{x.FullTypeName} {x.VariableName}");
        var constructorParams = new[] { $"{model.TypeName} source" }.Concat(interceptorParams);

         builder.AppendLine($$"""
    class VitalRouterGeneratedAsyncSubscriber : IAsyncCommandSubscriber
    {
        static class MethodTable<T> where T : ICommand
        {
            public static Func<{{model.FullTypeName}}, T, PublishContext, ValueTask>? Value;
            public static Func<VitalRouterGeneratedAsyncSubscriber, ICommandInterceptor[]>? InterceptorFinder;
        }

        static VitalRouterGeneratedAsyncSubscriber()
        {
""");
        foreach (var method in methods)
        {
            if (method.Interceptors.Count > 0)
            {
                builder.AppendLine($$"""
            MethodTable<{{method.CommandFullTypeName}}>.InterceptorFinder = static self => self.interceptorStack{{method.CommandTypePrefix}};
""");
            }
            else if (model.DefaultInterceptors.Count > 0)
            {
                builder.AppendLine($$"""
            MethodTable<{{method.CommandFullTypeName}}>.InterceptorFinder = static self => self.interceptorStackDefault;
""");
            }
            else
            {
                builder.AppendLine($$"""
            MethodTable<{{method.CommandFullTypeName}}>.Value = {{GetMethodTableEntry(method)}};
""");
            }
        }
        builder.AppendLine($$"""
        }

        readonly {{model.TypeName}} source;
""");
         if (model.AllInterceptors.Count > 0)
         {
             builder.AppendLine($"""
        readonly VitalRouterGeneratedAsyncSubscriberCore core;
""");
         }
         if (model.DefaultInterceptors.Count > 0)
         {
             builder.AppendLine($$"""
        readonly ICommandInterceptor[] interceptorStackDefault;
""");
         }
         foreach (var method in model.Routes.Where(x => x.Interceptors.Count > 0))
         {
             builder.AppendLine($$"""
        readonly ICommandInterceptor[] interceptorStack{{method.CommandTypePrefix}};
""");
         }

        builder.AppendLine($$"""

        public VitalRouterGeneratedAsyncSubscriber({{string.Join(", ", constructorParams)}})
        {
            this.source = source;
""");
        if (model.AllInterceptors.Count > 0)
        {
            builder.AppendLine("""
            this.core = new VitalRouterGeneratedAsyncSubscriberCore(source);
""");
        }

        if (model.DefaultInterceptors.Count > 0)
        {
            builder.AppendLine($$"""
            interceptorStackDefault = new ICommandInterceptor[] { {{string.Join(", ", model.DefaultInterceptors.Select(x => x.VariableName))}}, core };
""");
        }
        foreach (var method in model.Routes)
        {
            if (method.Interceptors.Count > 0)
            {
                builder.AppendLine($$"""
            interceptorStack{{method.CommandTypePrefix}} = new ICommandInterceptor[] { {{string.Join(", ", model.DefaultInterceptors.Concat(method.Interceptors).Select(x => x.VariableName))}}, core };
""");
            }
        }

        builder.AppendLine($$"""
        }

        public ValueTask ReceiveAsync<T>(T command, PublishContext context) where T : ICommand
        {
            if (MethodTable<T>.Value is { } method)
            {
                return method.Invoke(source, command, context);
            }
            if (MethodTable<T>.InterceptorFinder is { } finder)
            {
                var interceptorStack = finder.Invoke(this);
                return ReceiveContext<T>.InvokeAsync(command, interceptorStack, context);
            }
            return default;
        }
    }
""");
    }

    static void TryEmitAsyncSubscriberCore(TypeModel model, StringBuilder builder)
    {
        var methods = model.DefaultInterceptors.Count > 0
            ? model.Routes.ToArray()
            : model.Routes.Where(x => x.Interceptors.Count > 0).ToArray();

        if (methods.Length <= 0)
        {
            return;
        }

        builder.AppendLine($$"""
    class VitalRouterGeneratedAsyncSubscriberCore : ICommandInterceptor
    {
        static class MethodTable<T> where T : ICommand
        {
            public static Func<{{model.TypeName}}, T, PublishContext, ValueTask>? Value;
        }

        static VitalRouterGeneratedAsyncSubscriberCore()
        {
""");
        foreach (var methodMeta in methods)
        {
                builder.AppendLine($$"""
            MethodTable<{{methodMeta.CommandFullTypeName}}>.Value = {{GetMethodTableEntry(methodMeta)}};
""");
        }

        builder.AppendLine($$"""
        }

        readonly {{model.TypeName}} source;

        public VitalRouterGeneratedAsyncSubscriberCore({{model.TypeName}} source)
        {
            this.source = source;
        }

        public ValueTask InvokeAsync<T>(T command, PublishContext context, PublishContinuation<T> _) where T : ICommand
        {
            return MethodTable<T>.Value?.Invoke(source, command, context) ?? default;
        }
    }
""");
    }

    static string GetMethodTableEntry(RouteModel method)
    {
        if (method.IsAsync)
        {
            if (method.TakePublishContext)
            {
                if (method.IsValueTask)
                {
                    return $"static (source, command, context) => (ValueTask)source.{method.MethodName}(command, context)";
                }
                return $"static async (source, command, context) => await source.{method.MethodName}(command, context)";
            }
            if (method.TakeCancellationToken)
            {
                if (method.IsValueTask || method.IsUniTask)
                {
                    return $"static (source, command, context) => (ValueTask)source.{method.MethodName}(command, context.CancellationToken)";
                }
                return $"static async (source, command, context) => await source.{method.MethodName}(command, context.CancellationToken)";
            }
            if (method.IsValueTask || method.IsUniTask)
            {
                return $"static (source, command, context) => (ValueTask)source.{method.MethodName}(command)";
            }
            return $"static async (source, command, context) => await source.{method.MethodName}(command)";
        }

        if (method.TakePublishContext)
        {
            return $"static (source, command, context) => {{ source.{method.MethodName}(command, context); return default; }}";
        }

        if (method.TakeCancellationToken)
        {
            return $"static (source, command, context) => {{ source.{method.MethodName}(command, context.CancellationToken); return default; }}";
        }
        return $"static (source, command, context) => {{ source.{method.MethodName}(command); return default; }}";
    }
}
