using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using ChibiRuby;
using ChibiRuby.Serializer;

namespace VitalRouter.MRuby;

/// <summary>
/// Generates RBS (Ruby Signature) definitions for the mruby <c>cmd</c> method based on the
/// commands registered via <see cref="VitalRouterDefinition.AddCommand{TCommand}"/>.
/// </summary>
/// <remarks>
/// Each registered command becomes one overload of <c>cmd</c>. The command name is emitted as a
/// symbol literal type and the command's serializable members become optional keyword arguments,
/// mirroring how <c>ChibiRuby.Serializer</c> deserializes the keyword arguments into the command.
/// </remarks>
static class MRubyRbsGenerator
{
    public static string Generate(IReadOnlyList<KeyValuePair<string, Type>> commands)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# <auto-generated>");
        sb.AppendLine("# This file is generated by VitalRouter.MRuby. Do not edit manually.");
        sb.AppendLine("# </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("class Object");

        if (commands.Count <= 0)
        {
            sb.AppendLine("  def cmd: (Symbol, **untyped) -> void");
        }
        else
        {
            const string head = "  def cmd: ";
            var continuation = new string(' ', head.Length - 2) + "| ";

            for (var i = 0; i < commands.Count; i++)
            {
                var prefix = i == 0 ? head : continuation;
                sb.Append(prefix);
                sb.AppendLine(BuildOverload(commands[i].Key, commands[i].Value));
            }
        }

        sb.AppendLine("end");
        return sb.ToString();
    }

    static string BuildOverload(string commandName, Type commandType)
    {
        var sb = new StringBuilder();
        sb.Append('(');
        sb.Append(':').Append(commandName);

        foreach (var (key, type) in GetMembers(commandType))
        {
            sb.Append(", ?").Append(key).Append(": ").Append(MapToRbsType(type));
        }

        sb.Append(") -> void");
        return sb.ToString();
    }

    static IEnumerable<(string Key, Type Type)> GetMembers(Type commandType)
    {
        const BindingFlags flags = BindingFlags.Public | BindingFlags.Instance;

        foreach (var field in commandType.GetFields(flags))
        {
            if (field.IsDefined(typeof(MRubyIgnoreAttribute), inherit: true)) continue;
            yield return (ResolveKeyName(field), field.FieldType);
        }

        foreach (var property in commandType.GetProperties(flags))
        {
            if (property.IsDefined(typeof(MRubyIgnoreAttribute), inherit: true)) continue;
            if (property.GetIndexParameters().Length > 0) continue; // indexer
            if (property.GetMethod == null) continue; // set-only member is not serialized
            yield return (ResolveKeyName(property), property.PropertyType);
        }
    }

    static string ResolveKeyName(MemberInfo member)
    {
        var memberAttribute = member.GetCustomAttribute<MRubyMemberAttribute>();
        if (memberAttribute?.Name is { } alias)
        {
            return alias;
        }
        return ToSnakeCase(member.Name);
    }

    static string MapToRbsType(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying != null)
        {
            return MapToRbsType(underlying) + "?";
        }

        if (type.IsEnum) return "Symbol";
        if (type == typeof(string)) return "String";
        if (type == typeof(bool)) return "bool";
        if (type == typeof(Symbol)) return "Symbol";
        if (IsInteger(type)) return "Integer";
        if (type == typeof(float) || type == typeof(double) || type == typeof(decimal)) return "Float";

        if (type.IsArray)
        {
            var elementType = type.GetElementType()!;
            return $"Array[{MapToRbsType(elementType)}]";
        }

        if (type.IsGenericType)
        {
            if (TryGetDictionaryArguments(type, out var keyType, out var valueType))
            {
                return $"Hash[{MapToRbsType(keyType)}, {MapToRbsType(valueType)}]";
            }
            if (TryGetEnumerableElement(type, out var elementType))
            {
                return $"Array[{MapToRbsType(elementType)}]";
            }
        }

        if (type.IsDefined(typeof(MRubyObjectAttribute), inherit: false))
        {
            return "Hash[Symbol, untyped]";
        }

        return "untyped";
    }

    static bool IsInteger(Type type) =>
        type == typeof(byte) || type == typeof(sbyte) ||
        type == typeof(short) || type == typeof(ushort) ||
        type == typeof(int) || type == typeof(uint) ||
        type == typeof(long) || type == typeof(ulong) ||
        type == typeof(char);

    static bool TryGetDictionaryArguments(Type type, out Type keyType, out Type valueType)
    {
        foreach (var candidate in EnumerateSelfAndInterfaces(type))
        {
            if (!candidate.IsGenericType) continue;
            var definition = candidate.GetGenericTypeDefinition();
            if (definition == typeof(IDictionary<,>) || definition == typeof(IReadOnlyDictionary<,>))
            {
                var args = candidate.GetGenericArguments();
                keyType = args[0];
                valueType = args[1];
                return true;
            }
        }
        keyType = valueType = null!;
        return false;
    }

    static bool TryGetEnumerableElement(Type type, out Type elementType)
    {
        foreach (var candidate in EnumerateSelfAndInterfaces(type))
        {
            if (candidate.IsGenericType &&
                candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            {
                elementType = candidate.GetGenericArguments()[0];
                return true;
            }
        }
        elementType = null!;
        return false;
    }

    static IEnumerable<Type> EnumerateSelfAndInterfaces(Type type)
    {
        yield return type;
        foreach (var @interface in type.GetInterfaces())
        {
            yield return @interface;
        }
    }

    // Mirrors ChibiRuby.Serializer's snake_case conversion (NotationCaseMutator with '_').
    static string ToSnakeCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;

        var sb = new StringBuilder(name.Length + 4);
        for (var i = 0; i < name.Length; i++)
        {
            var ch = name[i];
            if (char.IsUpper(ch))
            {
                if (i > 0 && name[i - 1] is not ('_' or '-'))
                {
                    sb.Append('_');
                }
                sb.Append(char.ToLowerInvariant(ch));
            }
            else if (ch is '_' or '-')
            {
                sb.Append('_');
            }
            else
            {
                sb.Append(ch);
            }
        }
        return sb.ToString();
    }
}
